name: Compile

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-wasm:
    name: Compile WASM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install TinyGo
        run: |
          TINYGO_VERSION=0.33.0
          wget https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/tinygo_${TINYGO_VERSION}_amd64.deb
          sudo dpkg -i tinygo_${TINYGO_VERSION}_amd64.deb || sudo apt-get install -f -y

      - name: Create Target Directories
        run: mkdir -p frontend/src/assets/wasm

      - name: Compile WASM
        run: |
          cd go-wasm
          tinygo build -o ../frontend/src/assets/wasm/converter.wasm -target=wasm -no-debug -opt=z ./cmd/wasm
          cp $(tinygo env TINYGOROOT)/targets/wasm_exec.js ../frontend/src/assets/wasm/

      - name: Upload WASM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-binaries
          path: |
            frontend/src/assets/wasm/converter.wasm
            frontend/src/assets/wasm/wasm_exec.js
